blueprint:
  name: Aqara Button(s) — Toggle targets on single / double / hold
  description: >
    Add one or many Aqara button triggers (single/double/hold) and toggle different
    target lists per action. Works across integrations by using a Trigger selector:
    uses payload/subtype for the action; Trigger ID is optional for legacy setups.
  domain: automation

  input:
    button_triggers:
      name: Button triggers (one or many)
      description: >
        Add triggers for your Aqara button(s) here.
        IMPORTANT: The action is resolved from payload (MQTT) or subtype
        (device trigger). Trigger ID is optional for legacy configs.
        If you need it, set each trigger's "Trigger ID" to one of:
        - single
        - double
        - hold

        You can add multiple devices; just add more triggers and reuse the same IDs.
      selector:
        trigger:

    single_targets:
      name: Targets to toggle on SINGLE press
      default: {}
      selector:
        target:
          entity:
            - domain: light
            - domain: switch
            - domain: fan
            - domain: input_boolean
            - domain: automation

    double_targets:
      name: Targets to toggle on DOUBLE press
      default: {}
      selector:
        target:
          entity:
            - domain: light
            - domain: switch
            - domain: fan
            - domain: input_boolean
            - domain: automation

    hold_targets:
      name: Targets to toggle on HOLD
      default: {}
      selector:
        target:
          entity:
            - domain: light
            - domain: switch
            - domain: fan
            - domain: input_boolean
            - domain: automation

mode: queued
max: 10

variables:
  single_targets: !input single_targets
  double_targets: !input double_targets
  hold_targets: !input hold_targets
  action_kind: "{{ trigger.payload | default(trigger.subtype) | default(trigger.id) }}"

trigger: !input button_triggers

condition: []

action:
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ action_kind == 'single' and (single_targets | length > 0) }}"
        sequence:
          - action: homeassistant.toggle
            target: !input single_targets

      - conditions:
          - condition: template
            value_template: "{{ action_kind == 'double' and (double_targets | length > 0) }}"
        sequence:
          - action: homeassistant.toggle
            target: !input double_targets

      - conditions:
          - condition: template
            value_template: "{{ action_kind == 'hold' and (hold_targets | length > 0) }}"
        sequence:
          - action: homeassistant.toggle
            target: !input hold_targets
    default: []
