blueprint:
  name: Turn ON at sunset (offset), OFF at sunrise (offset)
  description: >
    Turns selected targets ON at sunset with an optional offset, and OFF at
    sunrise with an optional offset. Offsets accept ±HH:MM:SS
    (e.g., "-00:10:00" = 10 minutes before; "00:05:00" = 5 minutes after).
  domain: automation
  input:
    targets:
      name: Targets to control
      description: Choose entities/devices/areas (lights, switches, fans).
      selector:
        target:
          entity:
            domain:
              - light
              - switch
              - fan
    sunset_offset:
      name: Sunset offset
      description: Use ±HH:MM:SS (e.g., -00:10:00 or 00:05:00)
      default: "00:00:00"
      selector:
        text:
          multiline: false
    sunrise_offset:
      name: Sunrise offset
      description: Use ±HH:MM:SS (e.g., -00:05:00 or 00:02:00)
      default: "00:00:00"
      selector:
        text:
          multiline: false

mode: single

trigger:
  - id: sunset
    platform: sun
    event: sunset
    offset: !input sunset_offset
  - id: sunrise
    platform: sun
    event: sunrise
    offset: !input sunrise_offset

action:
  - choose:
      - conditions:
          - condition: trigger
            id: sunset
        sequence:
          - action: homeassistant.turn_on
            target: !input targets
      - conditions:
          - condition: trigger
            id: sunrise
        sequence:
          - action: homeassistant.turn_off
            target: !input targets
